#!/usr/bin/env bash
# GENERATED by tools/build-registry.sh from questions/*/meta. Do not edit by hand.
# Format: ID|Title|Domain|DomainShort|Difficulty|Folder|Needs|Weight|Minutes|Sources|Host
QUESTIONS=(
  "01|Kernel parameters now and after reboot|Operations Deployment|D1|Easy|q01-sysctl-persistent||4|5|0|any"
  "02|Find the disk-reading process, record its PID, lower its priority|Operations Deployment|D1|Medium|q02-process-io-hog|tool:pidstat|5|6|4|any"
  "03|Scheduled jobs for a user, root, and a one-off|Operations Deployment|D1|Medium|q03-cron-and-at||5|6|2|any"
  "04|A timer that runs a script every 15 minutes|Operations Deployment|D1|Medium|q04-systemd-timer||6|8|2|any"
  "05|Install, hold, verify, and report packages|Operations Deployment|D1|Easy|q05-packages||4|5|3|any"
  "06|Default target and GRUB timeout, persistent|Operations Deployment|D1|Medium|q06-boot-target-grub||5|6|2|any"
  "07|Define a VM from a disk image and set autostart|Operations Deployment|D1|Medium|q07-libvirt-define-vm|virt tool:qemu-img|6|8|3|any"
  "08|Run a web container with limits and a restart policy that survives reboot|Operations Deployment|D1|Hard|q08-podman-container|tool:podman|7|8|4|any"
  "09|Serve a custom document root on a custom port under SELinux enforcing|Operations Deployment|D1|Hard|q09-selinux-httpd-docroot|rocky tool:semanage|7|8|3|rocky"
  "10|Write a service unit for an application|Operations Deployment|D1|Medium|q10-systemd-service-unit||6|8|2|any"
  "11|A service fails to start: find why, fix it, make the journal persistent|Operations Deployment|D1|Medium|q11-journald-troubleshoot-service||6|8|2|any"
)

get_field() { echo "$1" | cut -d'|' -f"$2"; }

get_question_by_num() {
  local q
  for q in "${QUESTIONS[@]}"; do
    if [[ "$(get_field "$q" 1)" == "$1" ]]; then echo "$q"; return 0; fi
  done
  return 1
}

get_question_id()           { get_field "$1" 1; }
get_question_title()        { get_field "$1" 2; }
get_question_domain()       { get_field "$1" 3; }
get_question_domain_short() { get_field "$1" 4; }
get_question_difficulty()   { get_field "$1" 5; }
get_question_folder()       { get_field "$1" 6; }
get_question_needs()        { get_field "$1" 7; }
get_question_weight()       { get_field "$1" 8; }
get_question_minutes()      { get_field "$1" 9; }
get_question_sources()      { get_field "$1" 10; }
get_question_host()         { get_field "$1" 11; }

get_difficulty_color() {
  case "$1" in
    Easy)   echo "${GREEN}" ;;
    Medium) echo "${YELLOW}" ;;
    Hard)   echo "${RED}" ;;
    *)      echo "${WHITE}" ;;
  esac
}

get_domain_color() {
  case "$1" in
    D1) echo "${BLUE}" ;;
    D2) echo "${MAGENTA}" ;;
    D3) echo "${CYAN}" ;;
    D4) echo "${YELLOW}" ;;
    D5) echo "${RED}" ;;
    D6) echo "${GREEN}" ;;
    *)  echo "${WHITE}" ;;
  esac
}
