#!/usr/bin/env bash
# GENERATED by tools/build-registry.sh from questions/*/meta. Do not edit by hand.
# Format: ID|Title|Domain|DomainShort|Difficulty|Folder|Needs|Weight|Minutes|Sources|Host
QUESTIONS=(
  "01|Kernel parameters now and after reboot|Operations Deployment|D1|Easy|q01-sysctl-persistent||4|5|0|any"
  "02|Find the disk-reading process, record its PID, lower its priority|Operations Deployment|D1|Medium|q02-process-io-hog|tool:pidstat|5|6|4|any"
  "03|Scheduled jobs for a user, root, and a one-off|Operations Deployment|D1|Medium|q03-cron-and-at||5|6|2|any"
  "04|A timer that runs a script every 15 minutes|Operations Deployment|D1|Medium|q04-systemd-timer||6|8|2|any"
  "05|Install, hold, verify, and report packages|Operations Deployment|D1|Easy|q05-packages||4|5|3|any"
  "06|Default target and GRUB timeout, persistent|Operations Deployment|D1|Medium|q06-boot-target-grub||5|6|2|any"
  "07|Define a VM from a disk image and set autostart|Operations Deployment|D1|Medium|q07-libvirt-define-vm|virt tool:qemu-img|6|8|3|any"
  "08|Run a web container with limits and a restart policy that survives reboot|Operations Deployment|D1|Hard|q08-podman-container|tool:podman|7|8|4|any"
  "09|Serve a custom document root on a custom port under SELinux enforcing|Operations Deployment|D1|Hard|q09-selinux-httpd-docroot|rocky tool:semanage|7|8|3|rocky"
  "10|Write a service unit for an application|Operations Deployment|D1|Medium|q10-systemd-service-unit||6|8|2|any"
  "11|A service fails to start: find why, fix it, make the journal persistent|Operations Deployment|D1|Medium|q11-journald-troubleshoot-service||6|8|2|any"
  "12|Static IPv4 on the second NIC, persistent|Networking|D2|Medium|q12-static-ip-second-nic|nic2|6|8|1|any"
  "13|Persistent static route|Networking|D2|Easy|q13-static-route|nic2|5|6|1|any"
  "14|Hostname, hosts file, DNS servers and search domain|Networking|D2|Easy|q14-hostname-and-resolver||5|6|3|any"
  "15|Time source, NTP serving, timezone|Networking|D2|Easy|q15-chrony-time-sync|tool:chronyc|5|6|0|any"
  "16|Harden sshd, key-only login with one password exception|Networking|D2|Medium|q16-ssh-hardening-keys||6|8|2|any"
  "17|Allow only ssh, http, https and icmp, persistent, without blocking the exam ports|Networking|D2|Hard|q17-firewall-filter-persistent|netns|8|10|7|any"
  "18|Redirect a port and masquerade a subnet, persistent|Networking|D2|Hard|q18-port-redirect-nat|netns|7|8|7|any"
  "19|Put the second NIC into a bridge, persistent|Networking|D2|Medium|q19-bridge-second-nic|nic2|6|8|1|any"
  "20|Reverse proxy in front of an application|Networking|D2|Medium|q20-reverse-proxy-nginx||6|8|2|any"
  "21|Export a directory and mount it persistently|Networking|D2|Hard|q21-nfs-export-and-mount|tool:exportfs netns|7|8|3|any"
  "22|The web app is unreachable from the peer, find and fix two causes|Networking|D2|Medium|q22-network-troubleshoot-unreachable|netns|6|8|5|any"
  "23|Partition a disk, format it, and mount it by UUID|Storage|D3|Medium|q23-partition-format-fstab-uuid|disk|6|8|2|any"
  "24|Volume group with a custom extent size and a mounted logical volume|Storage|D3|Medium|q24-lvm-create|disk|7|8|4|any"
  "25|Grow a mounted logical volume after adding a disk|Storage|D3|Medium|q25-lvm-extend-online|disk|6|6|4|any"
  "26|Add a swap file with a priority, persistent|Storage|D3|Easy|q26-swap-file||4|5|1|any"
  "27|User quota on a filesystem|Storage|D3|Medium|q27-user-quota|disk|6|8|0|any"
  "28|Mirror two disks with mdadm and mount the array|Storage|D3|Medium|q28-raid1-mdadm|disk tool:mdadm|6|8|1|any"
  "29|Encrypted volume unlocked with a key file at boot|Storage|D3|Hard|q29-luks-encrypted-volume|disk tool:cryptsetup|7|8|0|any"
  "30|Attach a network block device and mount it|Storage|D3|Hard|q30-nbd-mount|netns tool:nbd-client|6|8|0|any"
  "31|Filesystem nearly full: recover space and find the hidden consumer|Storage|D3|Medium|q31-disk-full-triage|disk|5|6|2|any"
  "32|Clone, branch, ignore, commit, push|Essential Commands|D4|Easy|q32-git-basics|tool:git|5|6|1|any"
  "33|Read a certificate and issue a self-signed one|Essential Commands|D4|Medium|q33-openssl-inspect-and-selfsigned|tool:openssl|5|6|4|any"
  "34|Locate files by owner and size, list SUID binaries, set SGID and sticky|Essential Commands|D4|Medium|q34-find-and-special-permissions||5|6|3|any"
  "35|Reports from a log with grep, sort, uniq, sed and awk|Essential Commands|D4|Medium|q35-text-processing-pipeline||5|6|3|any"
  "36|Archive with exclusions, extract, symbolic and hard links|Essential Commands|D4|Easy|q36-archives-and-links||4|5|2|any"
  "37|A script with separate stdout and stderr files|Essential Commands|D4|Easy|q37-redirection-script||4|5|2|any"
  "38|A service cannot start because another one owns its port|Essential Commands|D4|Medium|q38-service-port-conflict||6|8|2|any"
  "39|Report CPU hog, load, cores, memory and process count|Essential Commands|D4|Easy|q39-resource-monitoring||4|5|3|any"
  "40|A service fails its file-descriptor limit: raise it with a drop-in|Essential Commands|D4|Medium|q40-service-limits-dropin||5|6|1|any"
  "41|Create users with exact attributes, a system account, and lock one|Users and Groups|D5|Medium|q41-users-groups-lifecycle||5|6|1|any"
  "42|Sudo rules and password ageing|Users and Groups|D5|Medium|q42-sudo-and-password-policy||6|8|2|any"
  "43|Group collaboration directory with ACLs|Users and Groups|D5|Medium|q43-acls-and-special-perms||5|6|1|any"
  "44|System-wide environment, skeleton, and per-user limits|Users and Groups|D5|Medium|q44-profiles-skel-and-limits||5|6|2|any"
  "45|Resolve users from an LDAP directory|Users and Groups|D5|Hard|q45-ldap-client-sssd|ubuntu tool:slapd|7|10|0|ubuntu"
)

get_field() { echo "$1" | cut -d'|' -f"$2"; }

get_question_by_num() {
  local q
  for q in "${QUESTIONS[@]}"; do
    if [[ "$(get_field "$q" 1)" == "$1" ]]; then echo "$q"; return 0; fi
  done
  return 1
}

get_question_id()           { get_field "$1" 1; }
get_question_title()        { get_field "$1" 2; }
get_question_domain()       { get_field "$1" 3; }
get_question_domain_short() { get_field "$1" 4; }
get_question_difficulty()   { get_field "$1" 5; }
get_question_folder()       { get_field "$1" 6; }
get_question_needs()        { get_field "$1" 7; }
get_question_weight()       { get_field "$1" 8; }
get_question_minutes()      { get_field "$1" 9; }
get_question_sources()      { get_field "$1" 10; }
get_question_host()         { get_field "$1" 11; }

get_difficulty_color() {
  case "$1" in
    Easy)   echo "${GREEN}" ;;
    Medium) echo "${YELLOW}" ;;
    Hard)   echo "${RED}" ;;
    *)      echo "${WHITE}" ;;
  esac
}

get_domain_color() {
  case "$1" in
    D1) echo "${BLUE}" ;;
    D2) echo "${MAGENTA}" ;;
    D3) echo "${CYAN}" ;;
    D4) echo "${YELLOW}" ;;
    D5) echo "${RED}" ;;
    D6) echo "${GREEN}" ;;
    *)  echo "${WHITE}" ;;
  esac
}
