apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
    - name: main
      image: nginx:1.21.6
      volumeMounts:
        - name: shared-data
          mountPath: /var/log/nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "256m"
        requests:
          memory: "64Mi"
          cpu: "128m"
    - name: sidecar
      image: busybox:1.35.0
      command: ["/bin/sh", "-c", "tail -n+1 -f /var/log/nginx/access.log"]
      volumeMounts:
        - name: shared-data
          mountPath: /var/log/nginx
      resources:
        limits:
          memory: "256Mi"
          cpu: "512m"
        requests:
          memory: "128Mi"
          cpu: "256m"
  volumes:
    - name: shared-data
      emptyDir: {}
