#!/usr/bin/env bash
# Generate ../mock-exams/mock-N.md from ../mock-exams/mock-N.set
# The .set file holds one "id|weight" per line; blank lines and # comments are ignored.
set -o pipefail
CLI="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
N="${1:?usage: build-mock.sh N}"
SET="$CLI/../mock-exams/mock-$N.set"
OUT="$CLI/../mock-exams/mock-$N.md"
TMP="$OUT.tmp"
trap 'rm -f "$TMP"' EXIT

[[ -f "$SET" ]] || { echo "missing $SET" >&2; exit 1; }

total=0; k=0
{
  echo "# CKS Mock Exam $N"
  echo
  echo "> GENERATED by \`tools/build-mock.sh $N\` from \`mock-$N.set\`. Edit the set file, then rerun the tool."
  echo
  echo '## Rules'
  echo
  echo '- 120 minutes. Pass mark 67 percent.'
  echo '- Run it with `./cks --mock '"$N"'` for setups, one timer and automatic scoring, or work from this paper and verify by hand.'
  echo '- Work on the host each task names, and return to the base host between tasks.'
  echo '- Allowed documentation only: kubernetes.io docs and blog, falco.org, the bom CLI reference, etcd.io, the ingress-nginx user guide, docs.cilium.io, istio.io.'
  echo '- Flag anything that passes 10 minutes and move on. Keep the last 15 minutes for verification.'
  echo '- No solutions until you have scored.'
  echo
  echo '## Tasks'
  echo
  while IFS='|' read -r id w; do
    id="${id%%[[:space:]]*}"
    [[ -z "$id" || "$id" == \#* ]] && continue
    d=$(find "$CLI/questions" -mindepth 1 -maxdepth 1 -name "q$id-*" | head -1)
    [[ -n "$d" ]] || { echo "unknown question id '$id' in $SET" >&2; exit 1; }
    # An incomplete question would silently produce a task with no title or host.
    for want in meta question.md; do
      [[ -s "$d/$want" ]] || { echo "question q$id is incomplete (no $want); refusing to build $OUT" >&2; exit 1; }
    done
    k=$(( k + 1 )); total=$(( total + w ))
    (
      # shellcheck disable=SC1090
      . "$d/meta"
      echo "### Task $k. $title ($w points)"
      echo
      echo "**Host:** $host. **Domain:** $domain. **Time budget:** $minutes min."
      echo
    )
    sed '1{/^# /d;}' "$d/question.md"
    echo
  done < "$SET"
  echo '---'
  echo
  echo "**Total: $total points. Pass mark: $(( (total * 67 + 99) / 100 )) points.**"
} > "$TMP"

if [[ "$k" -eq 0 ]]; then
  echo "No tasks parsed from $SET; leaving $OUT untouched. See $TMP" >&2
  exit 1
fi
mv "$TMP" "$OUT"
echo "wrote $OUT ($k tasks, $total points)"
