#!/usr/bin/env bash
# Generate cks-exam-qa-guide.md, the reading copy of the question bank, from
# questions/*/{meta,question.md,solution.md}. Edit the per-question files and
# rerun this; never edit the guide by hand.
set -o pipefail
CLI="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$CLI/cks-exam-qa-guide.md"
TMP="$OUT.tmp"
trap 'rm -f "$TMP"' EXIT

meta_count=$(find "$CLI/questions" -mindepth 2 -maxdepth 2 -name meta 2>/dev/null | wc -l | tr -d ' ')
if [[ "$meta_count" -eq 0 ]]; then
  echo "No questions/*/meta files found; refusing to overwrite $OUT" >&2
  exit 1
fi

# Refuse to build from an incomplete question. Without this a folder that is
# still being written produces a guide with silently empty sections.
incomplete=""
for d in "$CLI"/questions/q*/; do
  [[ -d "$d" ]] || continue
  for f in meta question.md solution.md setup.sh verify.sh cleanup.sh; do
    [[ -s "$d$f" ]] || incomplete="$incomplete\n  $(basename "$d") is missing $f"
  done
done
if [[ -n "$incomplete" ]]; then
  printf "Refusing to build the guide from incomplete questions:%b\n" "$incomplete" >&2
  exit 1
fi

slug() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9 -]//g; s/ /-/g'; }

# Inline a per-question file: drop its H1 title, and demote its headings two
# levels so they nest under the question's H3 rather than outranking it.
# Headings inside fenced code blocks are left alone, or a shell comment would be
# silently rewritten.
inline() {
  awk '
    NR == 1 && /^# / { next }
    /^```/           { fence = !fence }
    !fence && /^#{1,4} / { sub(/^#+/, "&##") }
    { print }
  ' "$1"
}

{
  echo '# CKS Exam Question and Answer Guide'
  echo
  echo '> GENERATED by `tools/build-guide.sh` from `questions/*/`. Edit the per-question files, then rerun the tool.'
  echo '>'
  echo '> Exam environment: Kubernetes v1.35. 15 to 20 tasks, 2 hours, 67 percent to pass, CKA prerequisite.'
  echo '> Allowed documentation: kubernetes.io docs and blog, falco.org, the bom CLI reference, etcd.io,'
  echo '> the ingress-nginx user guide, docs.cilium.io and istio.io. Nothing else, and there is no `jq`.'
  echo
  echo '## Question index'
  echo
  echo '| # | Domain | Question | Reports | Needs |'
  echo '|---|---|---|---|---|'
  for m in "$CLI"/questions/q*/meta; do
    [[ -e "$m" ]] || continue
    (
      # shellcheck disable=SC1090
      . "$m"
      n=$((10#$id))
      printf '| Q%s | %s | [%s](#q%s-%s) | %s sources | `%s` |\n' \
        "$n" "$domain_short" "$title" "$n" "$(slug "$title")" "$sources" "$needs"
    )
  done
  for m in "$CLI"/questions/q*/meta; do
    [[ -e "$m" ]] || continue
    d=$(dirname "$m")
    (
      # shellcheck disable=SC1090
      . "$m"
      n=$((10#$id))
      echo
      echo '---'
      echo
      echo "### Q$n. $title"
      echo
      echo "**Domain:** $domain. **Difficulty:** $difficulty. **Weight:** $weight. **Target:** $minutes min. **Host:** $host. **Needs:** \`$needs\`."
      echo
    )
    echo '**Question**'
    echo
    inline "$d/question.md"
    echo
    echo '**Solution**'
    echo
    inline "$d/solution.md"
  done
} > "$TMP"

if ! grep -q '^### Q1\.' "$TMP"; then
  echo "Generated guide looks wrong (no Q1 heading); leaving $OUT untouched. See $TMP" >&2
  exit 1
fi
mv "$TMP" "$OUT"
echo "wrote $OUT ($meta_count questions)"
