apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
    - image: nginx
      name: app
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "256m"
        limits:
          memory: "128Mi"
          cpu: "512m"
    - image: curlimages/curl:7.79.1
      name: sidecar
      args:
        - /bin/sh
        - -c
        - "while true; do curl localhost:80; sleep 5; done;"
      resources:
        requests:
          memory: "64Mi"
          cpu: "256m"
        limits:
          memory: "128Mi"
          cpu: "512m"
