---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXJtUXJNSXdTMXZDTG1BeFBockg1VC90SURDZDhIdGkyRk9kL0JlMm95U0luCnBVVVlmVU5CVmliY2Y3bXBOK0x2bVIwcklzTzJvTy9SOEhOeDJxVXlYQzRpWHFsQlZpMC9EaVhQaG9ORXAwTUgKdWhmaXZ6SVJqVDVSbnFubUZsMzJLZEJveFN1Wlg2MDdJUFB3VzNCWkhqTFg3OUJacTkwZkhUWVY1bDJCZWk1SQpsblZRRmNUczlXMTdYdnk2UVExRHppQlg3WEM4RDZLMllLM2VvcnhWQnBzdlhTMkJvWlYyMmJzRkxWTEdhblZzCnNRVjQ1YnpwNkc4TzhLKzlDcUorZlA3VFJFRTlVbG5jOXpVNjQ5WEhVQTFpdmlMKzdDc2JtUzRuY0ZDWHBlY0gKeTNZL0xGbk5hZDczY05oTE9hczJoWWY0S0pMdHR5TEtMVUpCTU9Odnl3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSU0rZXNaSTNRK1NaQXRpL0lFUng5dDFaS1IxeFZndkV2WWJkZGpoNVZLeTNsclVhYVRKCk1BUzlwam9lV1hqdERUQnVrMGR5RmlxTUlGZWFHR3BLeHVWM085RnUzbCtuUjhEaXVWV2JISXcxMHNPaEdlN0EKQXZSTFVxaXgwVmRkb0MxVVhjODUxOGlPYk0vMGw4Tm51cVJUeFVSRTAwY1VxRVRrU3Fjd2tSdWQxVFZ5bER0NAp6MnZRWVdWNHNybysxRUZUcC9CcnJtMk5SSUlMeDE5cG9YQUxzT2g3WVFqdGdCTXpzQlNpa1Q2elBDWnQ4eGpuCi9OOWpSNlgvQ0VucEx5RTJoL2tvMWNqaDRhN0dpVUdtaHRyRnRzemsvdmJvb3FBaytGbHdrVnJCeXN1SnJCRHIKMU5MVm1KUlVSaE1xVEYyRGtJdGNuOURFS0hZQ1Jja0xxZ0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth