#!/usr/bin/env bash
# GENERATED by tools/build-registry.sh from questions/*/meta. Do not edit by hand.
# Format: ID|Title|Domain|DomainShort|Difficulty|Folder|Needs|Weight|Minutes|Sources|Host
QUESTIONS=(
  "01|NetworkPolicy: Default-Deny + Selective Allow|Cluster Setup|D1|Medium|q01-networkpolicy-default-deny|kubectl cni-netpol|6|8|12|any"
  "02|CIS Benchmark Remediation with kube-bench|Cluster Setup|D1|Medium|q02-kube-bench-cis|node-root tool:kube-bench|8|10|12|control-plane"
  "03|Ingress TLS Termination|Cluster Setup|D1|Medium|q03-ingress-tls|kubectl ingress|5|6|7|any"
  "04|RBAC Least-Privilege Role + Binding|Cluster Hardening|D2|Medium|q04-rbac-least-privilege|kubectl|5|6|10|any"
  "05|ServiceAccount Token Hardening|Cluster Hardening|D2|Easy|q05-serviceaccount-hardening|kubectl|4|5|6|any"
  "06|Restrict the API Server (apiserver flags)|Cluster Hardening|D2|Hard|q06-apiserver-hardening|node-root|7|8|9|control-plane"
  "07|AppArmor Profile on a Pod|System Hardening|D3|Medium|q07-apparmor|node-root tool:apparmor_parser|7|8|12|worker"
  "08|Seccomp RuntimeDefault + Custom Profile|System Hardening|D3|Medium|q08-seccomp|node-root|6|8|5|worker"
  "09|Enforce Pod Security Admission (restricted)|Minimize Microservice Vulnerabilities|D4|Medium|q09-pod-security-admission|kubectl|4|5|6|any"
  "10|Encrypt Secrets at Rest (EncryptionConfiguration)|Minimize Microservice Vulnerabilities|D4|Hard|q10-encryption-at-rest|node-root tool:etcdctl|9|10|8|control-plane"
  "11|Admission Policy with Kyverno/Gatekeeper|Minimize Microservice Vulnerabilities|D4|Medium|q11-admission-policy|kubectl admission:kyverno|6|8|5|any"
  "12|Runtime Sandbox with RuntimeClass (gVisor)|Minimize Microservice Vulnerabilities|D4|Medium|q12-runtimeclass-gvisor|node-root tool:runsc|6|6|10|worker"
  "13|Scan Images with Trivy and Remediate|Supply Chain Security|D5|Medium|q13-trivy-scan|kubectl tool:trivy|5|6|9|any"
  "14|Restrict Images via ImagePolicyWebhook/Registry|Supply Chain Security|D5|Hard|q14-image-policy|node-root|9|12|12|control-plane"
  "15|Static Analysis & Manifest Hardening (kubesec)|Supply Chain Security|D5|Medium|q15-static-analysis|kubectl tool:kubesec|5|6|8|any"
  "16|Detect Threats with Falco Rules|Monitoring, Logging and Runtime Security|D6|Medium|q16-falco|node-root tool:falco|7|8|15|worker"
  "17|API Server Audit Logging Policy|Monitoring, Logging and Runtime Security|D6|Hard|q17-audit-logging|node-root|8|10|13|control-plane"
  "18|Immutable Containers (readOnlyRootFilesystem)|Monitoring, Logging and Runtime Security|D6|Easy|q18-immutable-containers|kubectl|4|5|6|any"
  "19|Falco: change the output format and save the alerts|Monitoring, Logging and Runtime Security|D6|Hard|q19-falco-output-format|node-root tool:falco|8|10|15|worker"
  "20|Audit log forensics: who deleted the Secret|Monitoring, Logging and Runtime Security|D6|Medium|q20-audit-log-forensics|linux|6|8|13|linux"
  "21|ImagePolicyWebhook: complete the config and deny unverified images|Supply Chain Security|D5|Hard|q21-imagepolicywebhook-broken-kubeconfig|node-root|9|10|12|control-plane"
  "22|kube-bench: fix the kubelet findings|Cluster Setup|D1|Medium|q22-kubelet-cis-hardening|node-root tool:kube-bench|7|8|12|worker"
  "23|The API server is down: find and fix the manifest|Cluster Hardening|D2|Medium|q23-apiserver-crash-recovery|node-root|7|8|9|control-plane"
  "24|Block the cloud metadata endpoint|Cluster Setup|D1|Easy|q24-networkpolicy-metadata-protection|kubectl cni-netpol|5|6|4|any"
  "25|Read a Secret straight from etcd|Minimize Microservice Vulnerabilities|D4|Medium|q25-read-secret-from-etcd|node-root tool:etcdctl|5|6|8|control-plane"
  "26|Encryption at rest: add a new key and re-encrypt|Minimize Microservice Vulnerabilities|D4|Hard|q26-reencrypt-existing-secrets|node-root tool:etcdctl|8|10|8|control-plane"
  "27|Fix two issues in the Dockerfile and two in the manifest|Supply Chain Security|D5|Easy|q27-dockerfile-manifest-hardening|linux|5|6|8|linux"
)

get_field() { echo "$1" | cut -d'|' -f"$2"; }

get_question_by_num() {
  local q
  for q in "${QUESTIONS[@]}"; do
    if [[ "$(get_field "$q" 1)" == "$1" ]]; then echo "$q"; return 0; fi
  done
  return 1
}

get_question_id()           { get_field "$1" 1; }
get_question_title()        { get_field "$1" 2; }
get_question_domain()       { get_field "$1" 3; }
get_question_domain_short() { get_field "$1" 4; }
get_question_difficulty()   { get_field "$1" 5; }
get_question_folder()       { get_field "$1" 6; }
get_question_needs()        { get_field "$1" 7; }
get_question_weight()       { get_field "$1" 8; }
get_question_minutes()      { get_field "$1" 9; }
get_question_sources()      { get_field "$1" 10; }
get_question_host()         { get_field "$1" 11; }

get_difficulty_color() {
  case "$1" in
    Easy)   echo "${GREEN}" ;;
    Medium) echo "${YELLOW}" ;;
    Hard)   echo "${RED}" ;;
    *)      echo "${WHITE}" ;;
  esac
}

get_domain_color() {
  case "$1" in
    D1) echo "${BLUE}" ;;
    D2) echo "${MAGENTA}" ;;
    D3) echo "${CYAN}" ;;
    D4) echo "${YELLOW}" ;;
    D5) echo "${RED}" ;;
    D6) echo "${GREEN}" ;;
    *)  echo "${WHITE}" ;;
  esac
}
