apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVTnFxV2hsYVZYdGRyVWNXUEhsY01ibGxNT1lJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSTFNRGt4TmpFek5EWXdORm9YRFRJMU1UQXhOakV6TkRZd05Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXRtOEIzTVdBNFdGSElkWVR2MVZrUURIc0JUejBWU1o5OCs5SApNbCsrZlJtRGtGdkhXZUU3d2VRTVhZc1hYNDF5NG9XeEZGTXZFZEt1NFNDWmU4N1RxdGU2ci9RQURXdExZVVI0CkxjWTU0cFJBRVZnbEtNUVF5bFQ2TjRCUWJhOEVjeGVyaSt4Y1hzOTBsc09EcG9yaHZ4YzNOTHNySHAyV1RsT3UKUXgvRjdZZkdWZC9iKzYwWkRKOEZqUVJFWi80dkZ1Tk44dlZKbDF1RGtEc2pIY2ZVcjRBQStvWDVKdmFCdmZKRApBbG9qdDhQQloxcWlSSVJJQUM1Mjl3UEcvOVAzaUtiQWcxVkRla2QvbmdTYjR0ZFFxbzVtSkhHNUZFVzB2ZXZ3Cmc2UW9kRG05a0dxdVQ0T0VmNmdUTWExY0poZHlReFpiLzlyVU1JNFU1QTU3UjhkQnl3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVMExSR21pZCtzMVE3MWY0Nm9ETkNxazFicHNVd0h3WURWUjBqQkJnd0ZvQVUwTFJHbWlkKwpzMVE3MWY0Nm9ETkNxazFicHNVd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFsQ1pJS3k5dC9PcGszNmlOK1AxaFRxZHlwdlU4N09haUhYZWJhaCt3Wk9tQ1lPcmtTVnlqMXRLUkpVQ24KVDUzVExyd3lJM2FURTM3OXRYYThRa0RzZURUSklLWUVxRHR3WFBsWUQrUlY2QW12L0JlMUZGY0NpME8xamd3VwpKMU1NbXZCb3dIZDFqUWVuN0RpNnE2aUtFNlplZTlySW9iK3A5S1Blb0hWbmNFcStLd3ZHUmFXazgvQkVEc3lUCndTeURibCtYdGQxTHc5ZzM5TTZnamNDMEk2aWYyS3M0UThpT0pidFlyNlpUWkY5MmJDaHpOWkNJVDhEdTFUSmsKOGZkYmFTdkIvU0tsVWU3dHZCWFJjbWp0Z2plWnhEQ2ZnaFk3ampzVkllRDA4cDRmTHcrM0lwdEgvTUVJUUUwawpCNnJlekVpd3NWaFhaVlZMaVpNU1RxYXY0dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None