apiVersion: v1
kind: Pod
metadata:
  name: elephant
  namespace: default
spec:
  containers:
  - name: mem-stress
    image: polinux/stress
    resources:
      limits:
        memory: 20Mi
      requests:
        memory: 5Mi