apiVersion: v1
kind: Pod
metadata:
  name: critical-agent
spec:
  priorityClassName: high-priority
  containers:
  - name: agent
    image: busybox
    resources:
      requests:
        memory: "64Mi"
        cpu: "256m"
      limits:
        memory: "128Mi"
        cpu: "512m"
    command: ["sh", "-c", "while true; do echo running; sleep 5; done"]

