apiVersion: v1
kind: Pod
metadata:
  name: stress-1
spec:
  containers:
    - name: stress
      image: polinux/stress:1.0.4
      resources:
        limits:
          memory: "256Mi"
          cpu: "256m"
        requests:
          memory: "256Mi"
          cpu: "256m"
      args: [
          /bin/sh,
          -c,
          'stress --vm 1 --vm-bytes \
          $(shuf -i 20-200 -n 1)M --vm-hang 1',
        ]

---
apiVersion: v1
kind: Pod
metadata:
  name: stress-2
spec:
  containers:
    - name: stress
      image: polinux/stress:1.0.4
      resources:
        limits:
          memory: "256Mi"
          cpu: "256m"
        requests:
          memory: "256Mi"
          cpu: "256m"
      args: [
          /bin/sh,
          -c,
          'stress --vm 1 --vm-bytes \
          $(shuf -i 20-200 -n 1)M --vm-hang 1',
        ]
