#!/usr/bin/env bash
# Generate lib/questions.sh from questions/*/meta.
# Run this after adding or editing any meta file. The registry is generated so
# that parallel authors never have to edit one shared file.
set -o pipefail
CLI="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$CLI/lib/questions.sh"
TMP="$OUT.tmp"

# Refuse to write an empty registry. Without this guard a mistake that leaves no
# meta files (a bad path, a half-finished migration) silently destroys the file.
meta_count=$(find "$CLI/questions" -mindepth 2 -maxdepth 2 -name meta 2>/dev/null | wc -l | tr -d ' ')
if [[ "$meta_count" -eq 0 ]]; then
  echo "No questions/*/meta files found under $CLI/questions; refusing to overwrite $OUT" >&2
  exit 1
fi

{
  echo '#!/usr/bin/env bash'
  echo '# GENERATED by tools/build-registry.sh from questions/*/meta. Do not edit by hand.'
  echo '# Format: ID|Title|Domain|DomainShort|Difficulty|Folder|Needs|Weight|Minutes|Sources|Host'
  echo 'QUESTIONS=('
  for m in "$CLI"/questions/q*/meta; do
    [[ -e "$m" ]] || continue
    (
      # shellcheck disable=SC1090
      . "$m"
      folder=$(basename "$(dirname "$m")")
      printf '  "%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s"\n' \
        "$id" "$title" "$domain" "$domain_short" "$difficulty" "$folder" \
        "$needs" "$weight" "$minutes" "$sources" "$host"
    )
  done
  echo ')'
  cat <<'HELPERS'

get_field() { echo "$1" | cut -d'|' -f"$2"; }

get_question_by_num() {
  local q
  for q in "${QUESTIONS[@]}"; do
    if [[ "$(get_field "$q" 1)" == "$1" ]]; then echo "$q"; return 0; fi
  done
  return 1
}

get_question_id()           { get_field "$1" 1; }
get_question_title()        { get_field "$1" 2; }
get_question_domain()       { get_field "$1" 3; }
get_question_domain_short() { get_field "$1" 4; }
get_question_difficulty()   { get_field "$1" 5; }
get_question_folder()       { get_field "$1" 6; }
get_question_needs()        { get_field "$1" 7; }
get_question_weight()       { get_field "$1" 8; }
get_question_minutes()      { get_field "$1" 9; }
get_question_sources()      { get_field "$1" 10; }
get_question_host()         { get_field "$1" 11; }

get_difficulty_color() {
  case "$1" in
    Easy)   echo "${GREEN}" ;;
    Medium) echo "${YELLOW}" ;;
    Hard)   echo "${RED}" ;;
    *)      echo "${WHITE}" ;;
  esac
}

get_domain_color() {
  case "$1" in
    D1) echo "${BLUE}" ;;
    D2) echo "${MAGENTA}" ;;
    D3) echo "${CYAN}" ;;
    D4) echo "${YELLOW}" ;;
    D5) echo "${RED}" ;;
    D6) echo "${GREEN}" ;;
    *)  echo "${WHITE}" ;;
  esac
}
HELPERS
} > "$TMP"

written=$(grep -c '^  "' "$TMP")
if [[ "$written" -ne "$meta_count" ]]; then
  echo "Expected $meta_count entries but generated $written; leaving $OUT untouched. See $TMP" >&2
  exit 1
fi
if ! bash -n "$TMP"; then
  echo "Generated registry has a syntax error; leaving $OUT untouched. See $TMP" >&2
  exit 1
fi
mv "$TMP" "$OUT"
echo "wrote $OUT ($written questions)"
