#!/usr/bin/env bash
# Generate lfcs-exam-qa-guide.md, the reading copy of the question bank, from
# questions/*/{meta,question.md,solution.md}. Edit the per-question files and
# rerun this; never edit the guide by hand.
set -o pipefail
CLI="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$CLI/lfcs-exam-qa-guide.md"
TMP="$OUT.tmp"

meta_count=$(find "$CLI/questions" -mindepth 2 -maxdepth 2 -name meta 2>/dev/null | wc -l | tr -d ' ')
if [[ "$meta_count" -eq 0 ]]; then
  echo "No questions/*/meta files found; refusing to overwrite $OUT" >&2
  exit 1
fi

# Refuse to build from an incomplete question. Without this a folder that is
# still being written produces a guide with silently empty sections.
incomplete=""
for d in "$CLI"/questions/q*/; do
  [[ -d "$d" ]] || continue
  for f in meta question.md solution.md setup.sh verify.sh cleanup.sh; do
    [[ -s "$d$f" ]] || incomplete="$incomplete\n  $(basename "$d") is missing $f"
  done
done
if [[ -n "$incomplete" ]]; then
  printf "Refusing to build the guide from incomplete questions:%b\n" "$incomplete" >&2
  exit 1
fi

slug() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9 -]//g; s/ /-/g'; }

{
  echo '# LFCS Exam Question and Answer Guide'
  echo
  echo '> GENERATED by `tools/build-guide.sh` from `questions/*/`. Edit the per-question files, then rerun the tool.'
  echo '>'
  echo '> Exam format: 17 to 20 performance-based tasks, 2 hours, 67 percent to pass, no prerequisites.'
  echo '> Allowed documentation: man pages, /usr/share/doc and installed packages. There is no browser.'
  echo '> Every change must survive a reboot. Never block ports 8080, 4505 or 4506.'
  echo
  echo '## Question index'
  echo
  echo '| # | Domain | Question | Reports | Needs |'
  echo '|---|---|---|---|---|'
  for m in "$CLI"/questions/q*/meta; do
    [[ -e "$m" ]] || continue
    (
      # shellcheck disable=SC1090
      . "$m"
      n=$((10#$id))
      printf '| Q%s | %s | [%s](#q%s-%s) | %s sources | `%s` |\n' \
        "$n" "$domain_short" "$title" "$n" "$(slug "$title")" "$sources" "$needs"
    )
  done
  for m in "$CLI"/questions/q*/meta; do
    [[ -e "$m" ]] || continue
    d=$(dirname "$m")
    (
      # shellcheck disable=SC1090
      . "$m"
      n=$((10#$id))
      echo
      echo '---'
      echo
      echo "### Q$n. $title"
      echo
      echo "**Domain:** $domain. **Difficulty:** $difficulty. **Weight:** $weight. **Target:** $minutes min. **Host:** $host. **Needs:** \`$needs\`."
      echo
    )
    echo '**Question**'
    echo
    sed '1{/^# /d;}' "$d/question.md"
    echo
    echo '**Solution**'
    echo
    sed '1{/^# /d;}' "$d/solution.md"
  done
} > "$TMP"

if ! grep -q '^### Q1\.' "$TMP"; then
  echo "Generated guide looks wrong (no Q1 heading); leaving $OUT untouched. See $TMP" >&2
  exit 1
fi
mv "$TMP" "$OUT"
echo "wrote $OUT ($meta_count questions)"
