apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
spec:
  storageClassName: "slow"
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/tmp/logs"
    type: DirectoryOrCreate
