apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    tier: frontend
  annotations:
    description: "This is a simple Nginx pod for serving static content."
spec:
  containers:
  - name: nginx-pod
    image: nginx:latest
    ports:
    - containerPort: 80
